### ISSUE TITLE
Add navbar to app

### ISSUE THREAD

**Issue by lauravuo** [kaupunginnaiset/alman-akka#7]
_Note! All designs are currently first drafts. Fonts, icons, colors etc. will most probably be changed later on, so developer can freely choose what to use at this phase. Also, the styles do not need to polished and finalized yet, main thing is to get things working 😊 Also, if you have better ideas, let's discuss!_

Add navbar to app with buttons (see below). Buttons can be now just placeholders, no functionality needed.
Mandatory features for first version:
- app name/icon
- filtering events (search icon)
- login user (user icon)

## Mobile 

<img width="578" alt="navbar-mobile" src="https://user-images.githubusercontent.com/29113682/158652724-fcf3987c-b2be-4020-a072-1bebab41372e.png">

## Desktop

<img width="1556" alt="navbar-desktop" src="https://user-images.githubusercontent.com/29113682/158654849-21fa4374-2079-4f51-b05a-caf63491273f.png">

**Comment by eevajonnapanula** [comment]
A question: Did you have some icon library in mind when drawing these? Or just take something and then change when final decisions have been made? I've been working with so many designers who have had so strict opinions about this kind of things that I figured I will always ask 😄

**Comment by lauravuo** [comment]
I don't have any preferences regarding styling choices including the icons 😄 Initially we discussed with @magdapoppins that we could use tailwind for styling, but we can ditch that idea as well.
